# Generated by Django 6.0.5 on 2026-05-12 20:47

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Клиент'), ('employee', 'Сотрудник'), ('admin', 'Администратор')], default='customer', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True, validators=[apps.accounts.models.validate_age])),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) XXX-XX-XX', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
