# Generated by Django 6.0.5 on 2026-05-18 11:36

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[apps.accounts.models.validate_age]),
        ),
    ]
