# Generated by Django 6.0.5 on 2026-05-18 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате: +375 (25/29/33/44) 123-45-67', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
