# Generated by Django 6.0.5 on 2026-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
