# Generated by Django 6.0.5 on 2026-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
